url: "https://otherpeoplesd.com" # the base hostname and protocol to the site (without an ending /)
title: "Other People" 
future: false
published: true

permalink: /:categories/:title # Removes default posts dates and hides file extension details

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/